version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.0

executors:
  golang:
    docker:
      - image: circleci/golang:1.17.5
    working_directory: ~/repo

commands:
  restore_go_cache:
    steps:
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
  download_mod:
    steps:
      - run:
          name: Install Dependencies
          command: go mod download
  save_go_cache:
    steps:
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

jobs:
  test:
    executor: golang
    steps:
      - checkout
      - restore_go_cache
      - download_mod
      - save_go_cache
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports
  fmt:
    executor: golang
    environment:
      RUN_CONTEXT: ""
    steps:
      - checkout
      - restore_go_cache
      - download_mod
      - save_go_cache
      - run:
          name: Run fmt
          command: make go/fmt
  lint:
    executor: golang
    environment:
      RUN_CONTEXT: ""
    steps:
      - checkout
      - restore_go_cache
      - download_mod
      - save_go_cache
      - run:
          name: Install golangci-lint
          command: curl -L https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
      - run:
          name: Run lint
          command: make go/lint
  build:
    executor: golang
    steps:
      - checkout
      - restore_go_cache
      - run:
          name: Build
          command: make go/build
      - run:
          name: mkdir workspace
          command: mkdir -p /tmp/workspace
      - run:
          name: Make zip
          command: zip /tmp/workspace/function.zip main
      - persist_to_workspace:
          root: /tmp/workspace
          paths: function.zip
      - store_artifacts:
          path: /tmp/workspace/function.zip
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - aws-cli/install
      - run:
          name: apply environments to Lambda function
          command: |-
            aws lambda update-function-configuration \
              --function-name akapun \
              --environment Variables={AKASHI_CORP_ID=${AKASHI_CORP_ID}\,AKASHI_TOKEN=${AKASHI_TOKEN}\,ROLLBAR_TOKEN=${ROLLBAR_TOKEN}}
      - run:
          name: deploy Lambda function
          command: aws lambda update-function-code --function-name akapun --zip-file fileb:///tmp/workspace/function.zip

workflows:
  version: 2
  main:
    jobs:
      - test
      - fmt
      - lint
      - build
      # There is no need to deploy akapun anymore because it is not currently in use.
      # So the environment variables have already been removed.
      # If resume to use, it is required to set new environment variables.
      # - deploy:
      #     context:
      #       - aws-akashi-button
      #     requires:
      #       - test
      #       - fmt
      #       - lint
      #       - build
      #     filters:
      #       branches:
      #         only: main
